/**
 * Turning a result into a file someone else can read.
 *
 * The rule here is that a number leaving this application has to carry enough
 * with it to be checkable by somebody who was not in the room. A CSV of melting
 * temperatures is a table of plausible numbers; the same CSV with the head, the
 * model version, the buffer, the applicability state and the exclusions is a
 * result. Six months later the difference is whether the figure can be defended.
 *
 * So every export here is two parts: a header block of provenance, and the rows.
 * The header is commented (`#`) so the file still opens in a spreadsheet and
 * still parses with `pandas.read_csv(..., comment="#")`, and the JSON export
 * keeps the run record as a sibling of the rows rather than flattening it away.
 *
 * Exclusions are exported alongside the results, never dropped. A batch of 200
 * that produces 197 rows with no note is a batch whose three missing sequences
 * are noticed after the figure is drawn, if at all.
 */
import type { BatchResult, ConditionScan, MutationScan, RunRecord, VariantScan } from "./client";

/**
 * The identity block, identical across all three exports.
 *
 * It used to be written out by hand per exporter, and drifted exactly the way
 * hand-copied blocks do: the batch CSV carried the model artifact hash and the
 * atlas fingerprint, the mutation and condition CSVs carried neither, and none
 * of the three carried the prediction schema version. A model *version* names a
 * release; the artifact hash names the file, which is what someone
 * reproducing a figure actually needs.
 */
function provenance(rec: RunRecord | undefined, fallback: [string, unknown][]): [string, unknown][] {
  if (!rec) return fallback;
  return [
    ["workflow", rec.workflow],
    ["model_version", rec.quadcond_model_version],
    ["model_artifact_sha256", rec.model_artifact_sha256],
    ["atlas_fingerprint", rec.atlas_fingerprint],
    ["prediction_schema_version", rec.prediction_schema_version],
    ...fallback,
  ];
}

/** RFC 4180 quoting. Sequences are safe; claim strings and notes are not. */
function cell(value: unknown): string {
  if (value === null || value === undefined) return "";
  const s = String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function rows(header: string[], body: unknown[][]): string {
  return [header.join(","), ...body.map((r) => r.map(cell).join(","))].join("\n");
}

/**
 * The provenance block every export opens with.
 *
 * Commented rather than a separate file, because a separate file is a file that
 * gets left behind when the table is emailed.
 */
function preamble(title: string, lines: [string, unknown][]): string {
  return [
    `# ${title}`,
    ...lines.map(([k, v]) => `# ${k}: ${cell(v)}`),
    "# Generated by AENNA-3D from QuadCond. Values are predictions, not measurements.",
    "#",
  ].join("\n");
}

export function mutationScanToCsv(scan: MutationScan): string {
  const heads = Object.keys(scan.heads);
  const head = preamble("QuadCond mutation scan", [
    ...provenance(scan.run_record, [
      ["wild_type", scan.wild_type.sequence],
      ["complement", scan.wild_type.complement],
      ["condition", scan.wild_type.condition],
      ["condition_detail", JSON.stringify(scan.wild_type.condition_detail)],
      ["condition_fields_defaulted",
       scan.wild_type.condition_imputed_fields.join(" ") || "none"],
      ["quadcond_version", scan.quadcond_version],
      ["heads", heads.join(" ")],
      ["strand_by_head", JSON.stringify(scan.wild_type.strand_by_head)],
      ["strand_sequence", JSON.stringify(scan.wild_type.strand_sequence)],
      ["ranking", scan.ranking_note],
      // The limitation itself, not just the numeric spread. A `delta_paired_sd`
      // column with no statement of what it is not is the marginal-interval
      // misreading this whole endpoint exists to avoid, exported.
      ["delta_semantics", scan.delta_note],
    ]),
    ...(scan.synthetic_model
      ? ([["SYNTHETIC_MODEL", scan.synthetic_model.warning]] as [string, unknown][])
      : []),
  ]);

  const body: unknown[][] = [];
  for (const row of scan.substitutions) {
    for (const name of heads) {
      const c = row.heads[name];
      if (!c) continue;
      body.push([
        row.label,
        row.position_1based,
        row.wild_type_base,
        row.mutant_base,
        name,
        scan.heads[name]?.units ?? "",
        c.strand,
        c.motif.state,
        c.wild_type.state,
        c.mutant.state,
        // Blank, not zero. An absent delta means the head was not applicable —
        // writing 0 would put "no effect" in a column a reader will average.
        c.wild_type_value ?? "",
        c.mutant_value ?? "",
        c.delta ?? "",
        c.delta_paired_sd ?? "",
        c.n_estimators ?? "",
      ]);
    }
  }
  return `${head}\n${rows(
    ["mutation", "position", "wild_type_base", "mutant_base", "head", "units",
     "strand", "motif_state", "wild_type_applicability", "mutant_applicability",
     "wild_type_value", "mutant_value", "delta", "delta_paired_sd", "n_estimators"],
    body,
  )}\n`;
}

export function conditionScanToCsv(scan: ConditionScan): string {
  const head = preamble("QuadCond condition scan", [
    ...provenance(scan.run_record, [
      ["sequence", scan.sequence],
      ["complement", scan.complement],
      ["strand_by_head",
       JSON.stringify(
         Object.fromEntries(
           Object.entries(scan.series).map(([n, s]) => [n, s.strand]),
         ),
       )],
      ["axis", `${scan.axis} (${scan.axis_label})`],
      ["base_condition", JSON.stringify(scan.base_condition)],
      ["condition_fields_defaulted",
       (scan.condition_imputed_fields ?? []).join(" ") || "none"],
      ["quadcond_version", scan.quadcond_version],
      // Exported because "this head was not in the chart" and "this head has no
      // response to this axis" are different findings, and only one of them is
      // about the sequence.
      ["inert_heads",
       scan.inert_heads.map((h) => `${h.head}(${h.axis_state})`).join(" ") || "none"],
      ["summary_basis", scan.summary_note ?? "in-domain points only"],
      ["neighbour_tiers", (scan.neighbour_tiers ?? ["experimental"]).join(" ")],
    ]),
    ...(scan.synthetic_model
      ? ([["SYNTHETIC_MODEL", scan.synthetic_model.warning]] as [string, unknown][])
      : []),
  ]);

  const body: unknown[][] = [];
  for (const [name, series] of Object.entries(scan.series)) {
    for (const p of series.points) {
      body.push([
        name,
        series.units,
        series.target_semantics,
        // The strand, per row. A condition CSV whose rows do not say which
        // strand they describe cannot be read back without the panel that
        // produced it.
        p.strand ?? series.strand,
        series.strand_sequence,
        p.value_of_axis,
        p.value ?? p.probability ?? "",
        p.interval?.[0] ?? "",
        p.interval?.[1] ?? "",
        p.folded_fraction ?? "",
        p.applicability.state,
        series.observed_response.verdict,
        series.observed_response.spread ?? "",
        series.observed_response.error_scale ?? "",
      ]);
    }
  }
  return `${head}\n${rows(
    ["head", "units", "claim_basis", "strand", "strand_sequence", scan.axis,
     "value", "interval_low", "interval_high", "folded_fraction",
     "applicability", "response_verdict", "response_spread", "head_error_scale"],
    body,
  )}\n`;
}

export function variantScanToCsv(scan: VariantScan): string {
  const rec = scan.run_record;
  const head = preamble("QuadCond variant join", [
    ...provenance(rec, [
      ["locus", `${scan.window.chromosome}:${scan.window.start}-${scan.window.end}`],
      ["window_sequence", scan.window.sequence],
      ["structural_axis_head", rec.structural_axis_head ?? ""],
      ["regulatory_axis_scorer", rec.regulatory_axis_scorer ?? "largest absolute score"],
      // Which source produced the regulatory column, and whether it failed.
      // A blank column has two causes and only one of them is about the locus.
      ["regulatory_source", rec.regulatory_source?.source ?? "none"],
      ["regulatory_source_detail", rec.regulatory_source?.path ?? ""],
      ["regulatory_error", rec.regulatory_error ?? "none"],
      ["threshold_basis", rec.threshold_basis ?? ""],
      ["structural_threshold", rec.structural_threshold ?? ""],
      ["regulatory_threshold", rec.regulatory_threshold ?? ""],
      ["quadrant_semantics", scan.quadrant_note],
      ["rank_semantics", scan.rank_note],
      ["delta_semantics", scan.delta_note],
    ]),
    ...(scan.synthetic_model
      ? ([["SYNTHETIC_MODEL", scan.synthetic_model.warning]] as [string, unknown][])
      : []),
  ]);

  const body: unknown[][] = scan.variants.map((v) => [
    v.label,
    v.variant.chromosome,
    v.variant.position,
    v.variant.reference,
    v.variant.alternate,
    v.mutation,
    v.structural.head ?? "",
    v.structural.strand ?? "",
    v.structural.motif_state ?? "",
    // Blank, not zero, on both axes. An absent delta means the head was not
    // applicable and an absent score means the source had no record; a zero in
    // either column is a number a reader will average.
    v.structural.delta ?? "",
    v.structural.delta_paired_sd ?? "",
    v.structural.rank ?? "",
    v.regulatory?.scorer ?? "",
    v.regulatory?.score ?? "",
    v.regulatory?.rank ?? "",
    v.combined_rank ?? "",
    v.quadrant,
    v.quadrant_reason ?? "",
  ]);

  return `${head}\n${rows(
    ["variant", "chromosome", "position", "reference", "alternate", "mutation",
     "structural_head", "strand", "motif_state", "delta", "delta_paired_sd",
     "structural_rank", "regulatory_scorer", "regulatory_score",
     "regulatory_rank", "combined_rank", "quadrant", "quadrant_reason"],
    body,
  )}\n`;
}

export function batchToCsv(result: BatchResult, heads: string[]): string {
  const rec = result.run_record;
  const head = preamble("QuadCond batch run", [
    ...provenance(rec, [
      ["input_mode", rec.input_mode ?? "records"],
      ["sequences_in", rec.n_sequences_in],
      ["sequences_scored", rec.n_sequences_scored],
      ["sequences_excluded", rec.n_sequences_excluded ?? result.excluded.length],
      ["duplicate_identifiers", (rec.duplicate_identifiers ?? []).join(" ") || "none"],
      ["rows", rec.n_rows],
      ["conditions", JSON.stringify(rec.conditions)],
      ["excluded", result.excluded.length],
      ...result.excluded.map(
        (e) => [`excluded:record_${(e.record_index ?? 0) + 1}:${e.id}`, e.reason] as
          [string, unknown],
      ),
    ]),
    ...(result.synthetic_model
      ? ([["SYNTHETIC_MODEL", result.synthetic_model.warning]] as [string, unknown][])
      : []),
  ]);

  const body: unknown[][] = [];
  for (const row of result.results) {
    const preds = (row.predictions ?? {}) as Record<string, Record<string, unknown>>;
    for (const name of heads) {
      const e = preds[name];
      if (!e) continue;
      const ap = (e.applicability ?? {}) as Record<string, unknown>;
      body.push([
        row.id,
        // The input index, because identifiers are the user's labels and two
        // records may share one. Without it a duplicated FASTA header makes two
        // rows indistinguishable in the export.
        row.record_index ?? "",
        row.sequence,
        row.condition,
        name,
        e.target_semantics ?? "",
        e.refused ? "" : (e.value ?? e.probability ?? e.argmax ?? ""),
        Array.isArray(e.interval) ? e.interval[0] : "",
        Array.isArray(e.interval) ? e.interval[1] : "",
        e.refused ? "refused" : ap.in_domain === false ? "out_of_domain" : "in_domain",
        e.refused ? e.refusal_reason : (ap.warnings as string[] | undefined)?.join(" | ") ?? "",
      ]);
    }
  }
  return `${head}\n${rows(
    ["id", "record_index", "sequence", "condition", "head", "claim_basis",
     "value", "interval_low", "interval_high", "applicability", "notes"],
    body,
  )}\n`;
}

/** The whole response, run record and exclusions intact. */
export function toJson(payload: unknown): string {
  return `${JSON.stringify(payload, null, 2)}\n`;
}

/**
 * Hand the file to the browser.
 *
 * Kept in one place so every export goes out with a content type and a name
 * that says what it is; a downloaded `download.csv` with no provenance in the
 * filename is one rename away from being unidentifiable.
 */
export function download(filename: string, body: string, mime = "text/csv"): void {
  const blob = new Blob([body], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Revoked on the next tick: revoking synchronously races the download in
  // Safari and produces an empty file.
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

/** `aenna_mutation-scan_AGGGTT_2026-09-09.csv` — identifiable after a rename. */
export function exportName(kind: string, sequence: string, ext: string): string {
  const stamp = new Date().toISOString().slice(0, 10);
  const tag = sequence.slice(0, 12).toUpperCase() || "sequence";
  return `aenna_${kind}_${tag}_${stamp}.${ext}`;
}
