#!/usr/bin/env python3
"""Rewrite the README's head table from the artifact.

The table listed eleven heads for two releases after there were twelve, and its
`g4_tm` row said 255 buffers while the report said 261. Both are the same defect:
a hand-maintained table describing a machine-generated object.

The table lives between two markers so this script can replace it without
touching the prose around it:

    <!-- HEADS TABLE: generated by scripts/16_sync_readme_tables.py -->
    ...
    <!-- END HEADS TABLE -->

Run it after any training run or metadata correction; `--check` fails when the
committed table no longer matches the artifact.

    python scripts/16_sync_readme_tables.py [--check]
"""
from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from quadcond import claims

START = "<!-- HEADS TABLE: generated by scripts/16_sync_readme_tables.py -->"
END = "<!-- END HEADS TABLE -->"

ORDER = [
    "g4_fold", "g4_topology", "g4_tm", "g4_tm_distilled", "im_fold", "im_pht",
    "im_pht_condition", "im_tm_condition", "im_fold_genomic", "g4_fold_genomic",
    "locus_peak_overlap_state", "im_architecture",
]

# The heads whose numbers carry the release, emphasised in the table.
EMPHASIS = {"g4_tm", "im_pht", "im_pht_condition", "im_tm_condition", "im_fold_genomic"}


def counts(db: Path) -> dict | None:
    """Row and buffer counts straight from the atlas, or None if it is absent."""
    if not db.exists():
        return None
    con = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    try:
        one = lambda q: con.execute(q).fetchone()[0]  # noqa: E731
        return {
            "buffers": one(
                "SELECT COUNT(DISTINCT k||'_'||na||'_'||li_nh4||'_'||mg||'_'||ph) "
                "FROM records WHERE source='g4stab_experimental_tm'"),
            "tm": one("SELECT COUNT(*) FROM records "
                      "WHERE source='g4stab_experimental_tm' AND tm IS NOT NULL"),
            "topologies": one("SELECT COUNT(*) FROM records "
                              "WHERE source='g4sp_topology' AND topology IS NOT NULL"),
            "im_pht": one("SELECT COUNT(*) FROM records "
                          "WHERE source='im_pht_biophysical' AND ph_t IS NOT NULL"),
        }
    finally:
        con.close()


def n_buffers(db: Path) -> int | None:
    if not db.exists():
        return None
    con = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    try:
        return con.execute(
            "SELECT COUNT(DISTINCT k||'_'||na||'_'||li_nh4||'_'||mg||'_'||ph) "
            "FROM records WHERE source='g4stab_experimental_tm'").fetchone()[0]
    finally:
        con.close()


def metric_of(h: dict) -> str:
    m = h.get("metrics", {})
    task = h.get("task")
    if task == "binary":
        out = f"AUROC {m.get('auroc', float('nan')):.3f}"
        if m.get("ece") is not None:
            out += f", ECE {m['ece']:.3f}"
        return out
    if task == "multiclass":
        return f"balanced accuracy {m.get('balanced_accuracy', float('nan')):.3f}"
    return f"R² {m.get('r2', float('nan')):.3f}"


def build(summary: dict, db: Path) -> str:
    heads = summary["heads"]
    if isinstance(heads, list):
        heads = {h["name"]: h for h in heads}
    c = counts(db)
    buffers = c["buffers"] if c else None

    rows = []
    if c:
        # The lead paragraph lives inside the generated block on purpose. It sat
        # directly above the table saying "255 buffers" while the generated row
        # beneath it said 261 -- a hand-written sentence and a machine-written
        # table describing the same corpus, disagreeing, three lines apart.
        rows += [
            f"Trained on the ingested experimental data: {c['topologies']:,} measured G4 "
            f"topologies, {c['tm']:,} measured melting temperatures across "
            f"{c['buffers']:,} buffers, and — for i-motifs — two panels of opposite "
            f"shape, {c['im_pht']:,} sequences at one buffer (iM-Seeker) and two "
            f"constructs across ten ionic strengths (5DUVMA). Grouped "
            f"cross-validation throughout.",
            "",
        ]
    rows += [
        "| head | data | claim basis | metric | grouped by |",
        "|---|---|---|---|---|",
    ]
    order = [n for n in ORDER if n in heads] + sorted(n for n in heads if n not in ORDER)
    for name in order:
        h = heads[name]
        tm = h.get("training_meta", h)
        sem = tm.get("target_semantics") or claims.target_semantics(name, tm)
        basis = {"biophysical": "measured", "genomic_proxy": "proxy",
                 "predicted": "model output", "derived": "derived"}.get(sem, sem)
        n = tm.get("n_rows") or h.get("n_rows") or "—"
        data = f"{n:,} rows" if isinstance(n, int) else str(n)
        if name == "g4_tm":
            # Without the atlas, say the honest thing rather than degrade to a
            # bare row count: `--check` in a source archive used to "fail"
            # simply because atlas.db was absent, and running it would have
            # replaced the buffer text with "2,274 rows".
            data = (f"{c['tm']:,} measured Tm, {buffers} buffers" if c
                    else f"{n:,} rows (atlas absent — buffer count not shown)")
        group = tm.get("group_by", "sequence")
        cells = [f"`{name}`", data, basis, metric_of(h), group]
        if name in EMPHASIS:
            cells = [f"**{c}**" for c in cells]
        rows.append("| " + " | ".join(cells) + " |")
    rows.append("")
    rows.append(f"*{len(order)} heads, counted from the artifact. A buffer is a distinct "
                f"(K⁺, Na⁺, Li⁺/NH₄⁺, Mg²⁺, pH) combination.*")
    return "\n".join(rows)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--readme", default="README.md")
    ap.add_argument("--summary", default="artifacts/quadcond_model.json")
    ap.add_argument("--db", default="data/atlas.db")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    summary = json.loads(Path(a.summary).read_text())
    db = Path(a.db)
    if not db.exists():
        # A check that fails for want of an optional 400 MB download is a check
        # people learn to ignore. Say what is missing and skip, rather than
        # reporting a table that was never actually compared.
        print(f"{db} is not present; the head table cannot be verified against "
              f"the atlas. Skipping (this is not a failure).")
        sys.exit(0)
    table = build(summary, db)

    text = Path(a.readme).read_text()
    if START not in text or END not in text:
        sys.exit(f"markers not found in {a.readme}; add:\n{START}\n{END}")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    fresh = f"{head}{START}\n\n{table}\n\n{END}{tail}"

    if fresh == text:
        print("README head table is current")
        return
    if a.check:
        sys.exit("README head table is stale; run without --check")
    Path(a.readme).write_text(fresh)
    print(f"rewrote the head table in {a.readme}")


if __name__ == "__main__":
    main()
